version: '3.7'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    image: puckel/docker-airflow:1.10.9
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./data:/data
      - ./scripts:/scripts
    ports:
      - ${AIRFLOW_PORT}:8080

  metabase:
    image: metabase/metabase
    ports:
      - ${METABASE_PORT}:3000
    depends_on:
      - db
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: ${POSTGRES_PORT}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: ${POSTGRES_HOST}

volumes:
  pgdata:
